---
- name: excuting the operation
  hosts: ubuntu
  become: yes
  become_method: sudo
  tasks:
   - name: install apache2
     apt: name=apache2 update_cache=yes state=latest

   - name: replace default with current path
     replace:
       path: /etc/apache2/sites-available/000-default.conf
       regexp: '/var/www/html'
       replace: "/var/www/html/current"
     notify:
      - restart apache2

  handlers:
  - name: restart apache2
    service: name=apache2 state=restarted
