---
- name: Upgrade all packages in linux-based machines
  yum: name=* state=latest
  tags: linux

- name: Reboot server
  become: true
  become_user: root
  command: /sbin/reboot
  tags: linux

- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  become: true
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10
  tags: linux


